services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - keycloak_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    environment:
      # HTTPS Configuration
      KC_HOSTNAME: ${KEYCLOAK_DOMAIN}
      KC_HOSTNAME_STRICT: "true"
      KC_HOSTNAME_STRICT_HTTPS: "true"
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/tls.key
      KC_HTTPS_PORT: 8443
      KC_HTTP_ENABLED: "false"
      
      # Database Configuration
      KC_DB: mysql
      KC_DB_URL_HOST: mysql
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${MYSQL_PASSWORD}
      
      # Admin Configuration
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      
      # Security Headers
      KC_HTTP_RELATIVE_PATH: /auth
      KC_PROXY: edge
      KC_PROXY_ADDRESS_FORWARDING: "true"
      
      # Geolocation & Security Features
      KC_FEATURES: "token-exchange,admin-fine-grained-authz,declarative-user-profile,client-policies,recovery-codes"
      
    volumes:
      - ./certs/tls.crt:/opt/keycloak/conf/tls.crt:ro
      - ./certs/tls.key:/opt/keycloak/conf/tls.key:ro
      - ./keycloak-themes:/opt/keycloak/themes:ro
    command: ["start", "--optimized"]
    ports:
      - "8443:8443"
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - keycloak_net
    healthcheck:
      test: ["CMD-SHELL", "curl -f https://localhost:8443/auth/health/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

  # Reverse Proxy with SSL Termination
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - keycloak
    restart: unless-stopped
    networks:
      - keycloak_net

volumes:
  mysql_data:

networks:
  keycloak_net:
    driver: bridge