version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: crowdeval-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: llm_evaluation
      MYSQL_USER: llm_user
      MYSQL_PASSWORD: llm_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data: