services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: jupiterailabs
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - keycloak_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    environment:
      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: "true"
      KC_DB: mysql
      KC_DB_URL_HOST: mysql
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: jupiterailabs
      KEYCLOAK_ADMIN: admin@keycloak.local
      KEYCLOAK_ADMIN_PASSWORD: dev_admin_password_2024!
    command: ["start-dev"]
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - keycloak_net

  keycloak-init:
    image: node:18-alpine
    volumes:
      - ./scripts:/scripts
    working_dir: /scripts
    command: [
      "/bin/sh", "-c",
      "apk add --no-cache curl; \
       echo 'Waiting for Keycloak to be ready...'; \
       sleep 60; \
       until curl -s http://keycloak:8080/health/ready > /dev/null; do \
         echo 'Keycloak not ready yet, waiting 5 seconds...'; \
         sleep 5; \
       done; \
       echo 'Keycloak is ready!'; \
       echo 'Waiting 30 seconds for Keycloak to fully initialize...'; \
       sleep 30; \
       echo 'Initializing Keycloak realms and clients...'; \
       npm install node-fetch dotenv; \
       node init-keycloak.js"
    ]
    depends_on:
      keycloak:
        condition: service_started
    environment:
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_ADMIN: admin@keycloak.local
      KEYCLOAK_ADMIN_PASSWORD: dev_admin_password_2024!
    networks:
      - keycloak_net

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8026:8025" # Web UI
      - "1026:1025" # SMTP
    restart: unless-stopped
    networks:
      - keycloak_net

volumes:
  mysql_data:

networks:
  keycloak_net:
    driver: bridge