version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: crowdeval-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password_2024!
      MYSQL_DATABASE: llm_evaluation
      MYSQL_USER: llm_user
      MYSQL_PASSWORD: secure_password123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data: